version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  build:
    docker:
      - image: "cimg/node:18.17" 
    steps:
      - node/install:
          node-version: '18.17'
      - checkout
      - run:
          name: Install Front-End Dependencies
          command: |
            cd udacity-shopping-store
            npm install
      - run:
          name: Build Front-End
          command: |
            cd udacity-shopping-store
            npm run build  # Build frontend
      - run:
          name: Install Back-End Dependencies
          command: |
            cd uda_project2
            npm install
      - run:
          name: Test Back-End Dependencies
          command: |
            cd uda_project2
            npm run test
      - run:
          name: Build Back-End
          command: |
            cd uda_project2
            npm run build  # Build backend

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '18.17'
      - eb/setup
      - aws-cli/setup
      - checkout
      # - run:
      #     name: Set up env variables
      #     command: |
      #       eb setenv AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      # - run:
      #     name: Deploy Application
      #     command: |
      #       cd uda_prj3
      #       npm install
      #       npm run build
      #       cd ../Project2
      #       npm install
      #       npm run build
      #       eb deploy 

workflows:
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
